class Producto:
    Codigo = ""
    Nombre = ""
    Marca = ""
    Categoria = ""
    Descripcion = ""
    PrecioDeVenta = ""
    CantidadPorBulto = ""
    FechaDeVencimiento = ""
    Foto = ""